
/** GET User Action type **/ 

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';



/** CREATE User Action type **/ 

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';



/** GET CATEGORY Action type **/ 

export const GET_CATEGORY_REQUEST = 'GET_CATEGORY_REQUEST';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAIL = 'GET_CATEGORY_FAIL';



/** CREATE CATEGORY Action type **/ 

export const CREATE_CATEGORY_REQUEST = 'CREATE_CATEGORY_REQUEST';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_FAIL = 'CREATE_CATEGORY_FAIL';

/** EDIT CATEGORY Action type **/ 

export const EDIT_CATEGORY_REQUEST = 'EDIT_CATEGORY_REQUEST';
export const EDIT_CATEGORY_SUCCESS = 'EDIT_CATEGORY_SUCCESS';
export const EDIT_CATEGORY_FAIL = 'EDIT_CATEGORY_FAIL';



/** GET CATEGORYEXPENSE Action type **/ 

export const GET_CATEGORYEXPENSE_REQUEST = 'GET_CATEGORYEXPENSE_REQUEST';
export const GET_CATEGORYEXPENSE_SUCCESS = 'GET_CATEGORYEXPENSE_SUCCESS';
export const GET_CATEGORYEXPENSE_FAIL = 'GET_CATEGORYEXPENSE_FAIL';



/** CREATE CATEGORYEXPENSE Action type **/ 

export const CREATE_CATEGORYEXPENSE_REQUEST = 'CREATE_CATEGORYEXPENSE_REQUEST';
export const CREATE_CATEGORYEXPENSE_SUCCESS = 'CREATE_CATEGORYEXPENSE_SUCCESS';
export const CREATE_CATEGORYEXPENSE_FAIL = 'CREATE_CATEGORYEXPENSE_FAIL';

/** EDIT CATEGORYEXPENSE Action type **/ 

export const EDIT_CATEGORYEXPENSE_REQUEST = 'EDIT_CATEGORYEXPENSE_REQUEST';
export const EDIT_CATEGORYEXPENSE_SUCCESS = 'EDIT_CATEGORYEXPENSE_SUCCESS';
export const EDIT_CATEGORYEXPENSE_FAIL = 'EDIT_CATEGORYEXPENSE_FAIL';
